<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="FileStorage\desktop.ini\**" />
	  <EmbeddedResource Remove="FileStorage\desktop.ini\**" />
	  <None Remove="FileStorage\desktop.ini\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
		<PackageReference Include="MailKit" Version="4.16.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.16.0" />

		<PackageReference Include="Minio" Version="7.0.0" />

		<PackageReference Include="Serilog" Version="4.3.1" />

		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />

		<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />

		<PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />

		<PackageReference Include="StackExchange.Redis" Version="2.12.1" />

		<PackageReference Include="Stripe.net" Version="50.4.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />

		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

</Project>
